#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Tateuchi
# SPDX-License-Identifier: BSD-3-Clause
import sys
ans1 = 0
ans2 = 0
ans3 = 1

for line in sys.stdin:
    for num in line.split():
        try:
            ans1 += int(num)
            ans2 -= int(num)
            ans3 *= int(num)
        except ValueError:
            try:
                ans1 += float(num)
                ans2 -= float(num)
                ans3 *= float(num)
            except ValueError:
                ans1 = ("")
                ans2 = ("")
                ans3 = ("")

print(ans1)
print(ans2)
print(ans3)

