#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Tateuchi
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
for line in sys.stdin:
        try:
            ans1 += int(line)
        except ValueError:
            try:
                ans1 += float(line)
            except ValueError:
                ans1 ="足し算時の入力が変だぞ(￣д￣)"
print("足し算の結果は"+str(ans1))

